# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: health report workflow

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '31 18 * * *'
    - cron: '31 19 * * *'
    - cron: '6 4 * * *'  
    - cron: '6 5 * * *'
jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright==1.8.0a1
        pip install telepot
    - name: Ensure browsers are installed
      run: python -m playwright install
    - name: Sun Yuexin
      run: python main.py ${{ secrets.NUM }} ${{ secrets.PWD }} ${{ secrets.TG_ID }} ${{ secrets.TG_TOKEN }}
    - name: Yang Ling
      run: python main.py ${{ secrets.NUM_YL }} ${{ secrets.PWD_YL }}
    - name: Shen Xiaoqi
      run: python main.py ${{ secrets.NUM_SXQ }} ${{ secrets.PWD_SXQ }}
