name: Yang-Ling

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '31 17 * * *'
    - cron: '31 20 * * *'
    - cron: '00 19 * * *'
    - cron: '50 4 * * *'
    - cron: '50 5 * * *' 
    - cron: '50 6 * * *'
jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright==1.8.0a1
        pip install telepot
    - name: Ensure browsers are installed
      run: python -m playwright install
      
    - name: Yang Ling
      run: python 123.py ${{ secrets.NUM_YL }} ${{ secrets.PWD_YL }} ${{ secrets.TG_ID }} ${{ secrets.TG_TOKEN }}
